// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: src/message/batch.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptedBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *BatchHeader `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Body   *BatchBody   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *EncryptedBatch) Reset() {
	*x = EncryptedBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_message_batch_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptedBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedBatch) ProtoMessage() {}

func (x *EncryptedBatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_message_batch_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptedBatch.ProtoReflect.Descriptor instead.
func (*EncryptedBatch) Descriptor() ([]byte, []int) {
	return file_src_message_batch_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptedBatch) GetHeader() *BatchHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *EncryptedBatch) GetBody() *BatchBody {
	if x != nil {
		return x.Body
	}
	return nil
}

type BatchHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LeaderID int32  `protobuf:"varint,1,opt,name=leaderID,proto3" json:"leaderID,omitempty"`
	Hash     string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *BatchHeader) Reset() {
	*x = BatchHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_message_batch_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchHeader) ProtoMessage() {}

func (x *BatchHeader) ProtoReflect() protoreflect.Message {
	mi := &file_src_message_batch_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchHeader.ProtoReflect.Descriptor instead.
func (*BatchHeader) Descriptor() ([]byte, []int) {
	return file_src_message_batch_proto_rawDescGZIP(), []int{1}
}

func (x *BatchHeader) GetLeaderID() int32 {
	if x != nil {
		return x.LeaderID
	}
	return 0
}

func (x *BatchHeader) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type BatchBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transactions []*TransactionHeader `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
}

func (x *BatchBody) Reset() {
	*x = BatchBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_message_batch_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BatchBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchBody) ProtoMessage() {}

func (x *BatchBody) ProtoReflect() protoreflect.Message {
	mi := &file_src_message_batch_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchBody.ProtoReflect.Descriptor instead.
func (*BatchBody) Descriptor() ([]byte, []int) {
	return file_src_message_batch_proto_rawDescGZIP(), []int{2}
}

func (x *BatchBody) GetTransactions() []*TransactionHeader {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_src_message_batch_proto protoreflect.FileDescriptor

var file_src_message_batch_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x62, 0x61,
	0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1d, 0x73, 0x72, 0x63, 0x2f, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x56, 0x0a, 0x0e, 0x45, 0x6e, 0x63, 0x72,
	0x79, 0x70, 0x74, 0x65, 0x64, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x24, 0x0a, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x42, 0x61, 0x74,
	0x63, 0x68, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x6f, 0x64, 0x79, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x22, 0x3d, 0x0a, 0x0b, 0x42, 0x61, 0x74, 0x63, 0x68, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x1a, 0x0a, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6c, 0x65, 0x61, 0x64, 0x65, 0x72, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x68,
	0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68, 0x22,
	0x43, 0x0a, 0x09, 0x42, 0x61, 0x74, 0x63, 0x68, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x36, 0x0a, 0x0c,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x0c, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_message_batch_proto_rawDescOnce sync.Once
	file_src_message_batch_proto_rawDescData = file_src_message_batch_proto_rawDesc
)

func file_src_message_batch_proto_rawDescGZIP() []byte {
	file_src_message_batch_proto_rawDescOnce.Do(func() {
		file_src_message_batch_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_message_batch_proto_rawDescData)
	})
	return file_src_message_batch_proto_rawDescData
}

var file_src_message_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_src_message_batch_proto_goTypes = []any{
	(*EncryptedBatch)(nil),    // 0: EncryptedBatch
	(*BatchHeader)(nil),       // 1: BatchHeader
	(*BatchBody)(nil),         // 2: BatchBody
	(*TransactionHeader)(nil), // 3: TransactionHeader
}
var file_src_message_batch_proto_depIdxs = []int32{
	1, // 0: EncryptedBatch.header:type_name -> BatchHeader
	2, // 1: EncryptedBatch.body:type_name -> BatchBody
	3, // 2: BatchBody.transactions:type_name -> TransactionHeader
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_src_message_batch_proto_init() }
func file_src_message_batch_proto_init() {
	if File_src_message_batch_proto != nil {
		return
	}
	file_src_message_transaction_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_src_message_batch_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*EncryptedBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_message_batch_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*BatchHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_message_batch_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BatchBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_message_batch_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_message_batch_proto_goTypes,
		DependencyIndexes: file_src_message_batch_proto_depIdxs,
		MessageInfos:      file_src_message_batch_proto_msgTypes,
	}.Build()
	File_src_message_batch_proto = out.File
	file_src_message_batch_proto_rawDesc = nil
	file_src_message_batch_proto_goTypes = nil
	file_src_message_batch_proto_depIdxs = nil
}
