// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v3.21.12
// source: src/message/partial.proto

package message

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PartialDecryption struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signer  uint64 `protobuf:"varint,1,opt,name=signer,proto3" json:"signer,omitempty"`
	PartDec []byte `protobuf:"bytes,2,opt,name=partDec,proto3" json:"partDec,omitempty"`
}

func (x *PartialDecryption) Reset() {
	*x = PartialDecryption{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_message_partial_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartialDecryption) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialDecryption) ProtoMessage() {}

func (x *PartialDecryption) ProtoReflect() protoreflect.Message {
	mi := &file_src_message_partial_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialDecryption.ProtoReflect.Descriptor instead.
func (*PartialDecryption) Descriptor() ([]byte, []int) {
	return file_src_message_partial_proto_rawDescGZIP(), []int{0}
}

func (x *PartialDecryption) GetSigner() uint64 {
	if x != nil {
		return x.Signer
	}
	return 0
}

func (x *PartialDecryption) GetPartDec() []byte {
	if x != nil {
		return x.PartDec
	}
	return nil
}

type PartialDecryptionBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Decryptions []*PartialDecryption `protobuf:"bytes,1,rep,name=decryptions,proto3" json:"decryptions,omitempty"`
	Sender      uint64               `protobuf:"varint,2,opt,name=sender,proto3" json:"sender,omitempty"`
	TxHash      string               `protobuf:"bytes,3,opt,name=txHash,proto3" json:"txHash,omitempty"`
}

func (x *PartialDecryptionBatch) Reset() {
	*x = PartialDecryptionBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_src_message_partial_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PartialDecryptionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartialDecryptionBatch) ProtoMessage() {}

func (x *PartialDecryptionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_message_partial_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartialDecryptionBatch.ProtoReflect.Descriptor instead.
func (*PartialDecryptionBatch) Descriptor() ([]byte, []int) {
	return file_src_message_partial_proto_rawDescGZIP(), []int{1}
}

func (x *PartialDecryptionBatch) GetDecryptions() []*PartialDecryption {
	if x != nil {
		return x.Decryptions
	}
	return nil
}

func (x *PartialDecryptionBatch) GetSender() uint64 {
	if x != nil {
		return x.Sender
	}
	return 0
}

func (x *PartialDecryptionBatch) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

var File_src_message_partial_proto protoreflect.FileDescriptor

var file_src_message_partial_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x61,
	0x72, 0x74, 0x69, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x11, 0x50,
	0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x44, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61, 0x72, 0x74,
	0x44, 0x65, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x72, 0x74, 0x44,
	0x65, 0x63, 0x22, 0x7e, 0x0a, 0x16, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x44, 0x65, 0x63,
	0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x34, 0x0a, 0x0b,
	0x64, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x50, 0x61, 0x72, 0x74, 0x69, 0x61, 0x6c, 0x44, 0x65, 0x63, 0x72, 0x79,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x64, 0x65, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78,
	0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61,
	0x73, 0x68, 0x42, 0x0d, 0x5a, 0x0b, 0x73, 0x72, 0x63, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_src_message_partial_proto_rawDescOnce sync.Once
	file_src_message_partial_proto_rawDescData = file_src_message_partial_proto_rawDesc
)

func file_src_message_partial_proto_rawDescGZIP() []byte {
	file_src_message_partial_proto_rawDescOnce.Do(func() {
		file_src_message_partial_proto_rawDescData = protoimpl.X.CompressGZIP(file_src_message_partial_proto_rawDescData)
	})
	return file_src_message_partial_proto_rawDescData
}

var file_src_message_partial_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_message_partial_proto_goTypes = []any{
	(*PartialDecryption)(nil),      // 0: PartialDecryption
	(*PartialDecryptionBatch)(nil), // 1: PartialDecryptionBatch
}
var file_src_message_partial_proto_depIdxs = []int32{
	0, // 0: PartialDecryptionBatch.decryptions:type_name -> PartialDecryption
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_message_partial_proto_init() }
func file_src_message_partial_proto_init() {
	if File_src_message_partial_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_src_message_partial_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*PartialDecryption); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_src_message_partial_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*PartialDecryptionBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_src_message_partial_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_message_partial_proto_goTypes,
		DependencyIndexes: file_src_message_partial_proto_depIdxs,
		MessageInfos:      file_src_message_partial_proto_msgTypes,
	}.Build()
	File_src_message_partial_proto = out.File
	file_src_message_partial_proto_rawDesc = nil
	file_src_message_partial_proto_goTypes = nil
	file_src_message_partial_proto_depIdxs = nil
}
